# Modified from WorldEngine (https://github.com/OpenDriveLab/WorldEngine), licensed under Apache-2.0.
import copy
import logging
import uuid
import numpy as np

from odyssey.base_class.configurable import Configurable
from odyssey.common.randomizable import Randomizable
from odyssey.components.parameter_space import Box

from odyssey.engine.engine_utils import get_engine


class BasePolicy(Randomizable, Configurable):

    def __init__(self, agent, random_seed=None, config=None):
        Randomizable.__init__(self, random_seed)
        Configurable.__init__(self, config)

        self.agent = agent
        self.action_info = dict()

    def _get_task_name(self):
        return str(uuid.uuid4())

    def act(self, *args, **kwargs):
        """
        Return an action vector consisting of two element: [steering, throttle/brake]. Runtime information generated by
        the policy can be written to self.action_info, which will be retrieved and shown in info dict automatically.
        """
        pass

    def get_action_info(self):
        """
        Get current action info for env.step() retrieve
        """
        return copy.deepcopy(self.action_info)

    def reset(self):
        self.action_info.clear()

    def destroy(self):
        """
        Destroy Base class
        """
        Configurable.destroy(self)
        Randomizable.destroy(self)
        logging.debug("{} is released".format(self.__class__.__name__))

    @property
    def name(self):
        return self.__class__.__name__

    def __repr__(self):
        return self.name

    @property
    def engine(self):
        return get_engine()

    @classmethod
    def get_input_space(cls):
        """
        It defines the input space of this class of policy. This will be the action space for the agent.
        """
        return Box(-1.0, 1.0, shape=(2, ), dtype=np.float32)

    def get_state(self):
        return self.get_action_info()

    @property
    def traj_step(self):
        return self.agent.traj_step
